#
# This file is part of duck-lab.
# 
# Copyright (c) 
# 2012 - Christian Nastasi, Claudio Salvadori 
#
# duck-lab is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# duck-lab is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301  USA
#
################################################################################
#  duck-lab Configuration Makefile 
#
#  author(s): Christian Nastasi (c.nastasi@sssup.it, nastasichr@gmail.com) 
#             Claudio Salvadori (c.salvadori@sssup.it)
#  version:   1.0 
#  date:      February 2012
################################################################################

################################################################################
### Platform Flag
OS_PLATFORM   		:= $(shell uname -o)
# TODO: A possible usage follows: (remove if not necessary)
#ifeq ($(OS_PLATFORM),GNU/Linux)
#else
#endif
################################################################################

################################################################################
#DUCK_INSTALL_PREFIX 	:= $(shell pwd)
DUCK_INSTALL_PREFIX 	:= /usr/local
################################################################################

################################################################################
### BUILD TYPE
### CHOOSE AMONG THESE  :  RELEASE, RELEASE_VERBOSE, DEBUG, DEBUG_VERBOSE
DUCK_BUILD_TYPE		:= DEBUG_VERBOSE 
################################################################################

################################################################################
### LOG FILE
### Comment/Uncomment to direct output log to std::clog / file
DUCK_DAFAULT_LOG_FILE	:= "duck-lab-RUNTIME.log"
################################################################################

################################################################################
### Comment/Uncomment if namespace has to be disabled/enabled
DUCK_USE_NAMESPACE	:= -DDUCK_USE_NAMESPACE
################################################################################

################################################################################
### ENABLEs Section (Comment/Uncomment to Enable/Disable)
#DUCK_USE_ROOT_CERN	:=  1 # Enable/Disable Integration with ROOT-cern lib
################################################################################
