#
# This file is part of duck-lab.
# 
# Copyright (c) 
# 2012 - Christian Nastasi, Claudio Salvadori 
#
# duck-lab is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# duck-lab is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301  USA
#
################################################################################
#  duck-lab duck_io library: (recursive) Rules Makefile 
#
#  author(s): Christian Nastasi (c.nastasi@sssup.it, nastasichr@gmail.com) 
#             Claudio Salvadori (c.salvadori@sssup.it)
#  version:   1.0 
#  date:      February 2012
################################################################################

##########################
# Automatic lists

SUB_LIBS 	:= ${SUB_DIRS:%=lib_part_%.a}
OBJ_FILES  	:= ${SRC_FILES:%.cpp=%.o}
DEP_FILES	:= $(patsubst %.cpp,%.d,$(SRC_FILES))


##########################
# Dependencies variables

# Add .d to make's recognized suffixes
SUFFIXES 	+= .d 
#List of targets not requiring deps
NODEPS		:= recursive_clean 


##########################
# Others

FILE_CLASSNAME 	= $(patsubst $(shell pwd)/%, %, $(patsubst %.cpp,%,$<)) 


##########################
# Makefile Rules 

# NOTE: This is the entry rules. Should be always here

$(OUT_LIB): $(OBJ_FILES) $(SUB_LIBS)
	@echo "LD partial " $(OUT_LIB) 
	@$(LD) -r $(LDFLAGS) $^ -o $@ 

$(SUB_LIBS) : subdirs

subdirs: 
	@echo "MAKE SUBDIR $(SUB_DIRS)"
	@for i in $(SUB_DIRS); do\
	    if [ ! -d $$i ]; then\
	        echo "SKIPPING (not existing)" $$i;\
	        continue;\
	    fi;\
	    cd $$i; \
	    MAIN_DIR="$(MAIN_DIR)"\
	    DUCK_DIR="$(DUCK_DIR)"\
	    MAKEOPT="$(MAKEOPT)"\
	    CXXOPT="$(CXXOPT)"\
	    CXXFLAGS="$(CXXFLAGS)"\
	    OUT_LIB="../lib_part_$$i.a" \
	    make $(MAKEOPT);\
	    cd -;\
	done;

recursive_clean: clean_subdirs
	rm -rf *.o *.d

clean_subdirs: 
	@echo "MAKE CLEAN SUBDIR $(SUB_DIRS)"
	@for i in $(SUB_DIRS); do\
	    if [ ! -d $$i ]; then\
	        echo "SKIPPING (not existing)" $$i;\
	        continue;\
	    fi;\
	    cd $$i; \
	    MAIN_DIR="$(MAIN_DIR)"\
	    DUCK_DIR="$(DUCK_DIR)"\
	    MAKEOPT="$(MAKEOPT)"\
	    make recursive_clean;\
	    cd -;\
	    rm -rf *.a;\
	done;

################################################
#       Overriding Implict Build Rule          #
################################################
ifdef DUCK_VERBOSE
%.o : %.cpp %.d 
	$(CXX) $(CXXOPT) -c $(CXXFLAGS) $< -o $@
else
%.o : %.cpp %.d 
	@$(CXX) $(CXXOPT) -c $(CXXFLAGS) $< -o $@
	@echo CXX $(FILE_CLASSNAME) 
endif

# This is the rule for creating the dependency files
ifdef DUCK_VERBOSE
%.d: %.cpp
	$(CXX) $(CXXOPT) $(CXXFLAGS) -MM -MT '$(patsubst %.cpp,%.o,$<)' $< > $@
else
%.d: %.cpp
	@$(CXX) $(CXXOPT) $(CXXFLAGS) -MM -MT '$(patsubst %.cpp,%.o,$<)' $< > $@
	@echo DEP $(FILE_CLASSNAME)
endif
################################################


#############################
# Dependency files inclusion

#Don't create dependencies when we're cleaning, for instance
ifeq (0, $(words $(findstring $(MAKECMDGOALS), $(NODEPS))))
-include $(DEP_FILES)
endif
